config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'
  resources :users
  resources :messages
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :content, presence: true
  scope :for_display, -> { order(:created_at).last(50) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  EMAIL_REGEX = /^\S+@\S+$/
  NAME_REGEX = /\w+/
  validates :email , presence: true,
                     uniqueness:{case_sensetive:false},
                     format:{with:EMAIL_REGEX,multiline:true}
                       
  validates :username, presence: true, 
                       uniqueness: { case_sensitive: false }, 
                       format: { with: /\A#{NAME_REGEX}\z/i },
                       length: { maximum: 15 }
                      
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :logged_in_user
  before_action :get_messages

  def index
  end

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast 'room_channel',
                                   message: render_message(message)
    end
  end

  private

    def get_messages
      @messages = Message.for_display
      @message  = current_user.messages.build
    end

    def message_params
      params.require(:message).permit(:content)
    end

    def render_message(message)
      render(partial: 'message', locals: { message: message })
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to messages_url
    else
      flash.now[:danger] = 'Invalid username/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to login_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to messages_url
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:username, :password, :email, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    cookies.signed[:user_id] = user.id
  end

  def log_out
    cookies.delete(:user_id)
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(id: cookies.signed[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="header">
  <ul class="header-nav">
    <% if logged_in? %>
    <li><%= link_to "Sign out", logout_path, method: :delete %>
    <% end %>
  </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
  </head>
  <body>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message">
  <div class="message-user">
    <%= message.user.username %>:
  </div>
  <div class="message-content">
    <%= message.content %>
  </div>
</div>

app/views/messages/_message_form.html.erb
<div class="message-input">
  <%= form_for(@message, remote: true) do |f| %>
    <%= f.text_area :content, placeholder: "#{current_user.username}, please write something." %>
    <%= f.submit "Send" %>
  <% end %>
</div>

app/views/messages/_messages.html.erb
<div id="messages" class="messages">
  <div id="messages-table" class="messages-table">
    <% if @messages.any? %>
      <%= render @messages %>
    <% end %>
  </div>
</div>

app/views/messages/index.html.erb
<div class="message-wr">
  <%= render 'messages' %>
  <%= render 'message_form' %>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="dialog">
  
  <%= form_for(@user) do |f| %>
    <%= f.text_field :username, placeholder:"User name" %>
    <%= f.text_field :email, placeholder:"Email" %>
    <%= f.password_field :password, placeholder:"Password" %>
    <%= f.password_field :password_confirmation, placeholder:"Password confirmation" %>
    <%= render 'shared/error_messages' %>
    <%= f.submit "Sign up" %>
  <% end %>
  
  <p class="session-links">
    Already have an account? <%= link_to "Sign in here", root_path %>
  </p>
</div>